<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ServiceAndIndustryPagesSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        // Service Pages
        $servicePages = [
            [
                'slug' => 'rigging-truss-services',
                'title' => 'Rigging & Truss Services',
                'description' => 'When you hire a firm to suspend thousands of pounds above the heads of a plethora of people – at a rock concert or industry conference, for example – then you need to be certain you\'re doing business with the best. Whatever size or type of event you are organizing, Stagepass Audio Visual Limited is here to help with all your rigging equipment needs. Safety is our number one concern, and we do not make mistakes.',
                'content' => '<p>It\'s what\'s on the inside that counts, right? We understand that all great events start with an even greater foundation. After careful planning in accordance to legal and technical specifications, our rigging specialists provide on-site service to ensure the proper and safe installation of all necessary hardware to prepare your venue for its transformation. Regardless of event size or scope, we\'re ready to tackle your project head-on.</p>',
                'meta_description' => 'Professional rigging and truss services for safe and secure event installations. StagePass Audio Visual provides expert rigging solutions.',
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'staging-services',
                'title' => 'Staging Services',
                'description' => 'When it comes to staging, safety is key. Got a wild idea that you want a car on stage? Yeah, we can take care of that. Our stages can (and have) withstood automobiles at multiple events, and all of our equipment is properly rated for safety and our staff is expert trained. We take the responsibility of our clients\' and performers\' safety very seriously.',
                'content' => null,
                'meta_description' => 'Professional staging services for events of all sizes. Safe, reliable staging solutions from StagePass Audio Visual.',
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'graphics',
                'title' => 'Graphics',
                'description' => 'No event is complete without eye-catching visual content. Whether your visual story is told through signs, posters, printed back panels, or totems, we\'ll make sure it\'s told right. From concept to completion, our graphics team will work with you to create stunning visual elements that enhance your event.',
                'content' => null,
                'meta_description' => 'Professional graphics and visual design services for events. Custom signage, posters, and visual elements.',
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'equipment-rentals-sales',
                'title' => 'Equipment Rentals & Sales',
                'description' => 'Our well sized warehouse in Nairobi is home to a massive inventory of some of the best technology available. We take great pride in making this equipment available for rental or purchase, ensuring you have access to top-quality AV equipment for your events.',
                'content' => null,
                'meta_description' => 'AV equipment rentals and sales in Nairobi. Professional audio-visual equipment for your events.',
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'design-services',
                'title' => 'Design Services',
                'description' => 'When organizing an intimate celebration or an arena concert, the objective is always flawless design. Lighting placement, staging, audio – the overall design of your event must be top-of-mind from the very beginning. Our design team works with you to create cohesive, stunning event designs.',
                'content' => null,
                'meta_description' => 'Professional event design services. Lighting, staging, and audio design for memorable events.',
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'audio',
                'title' => 'Audio',
                'description' => 'The right sound in any venue requires pre-show planning, signal distribution, diverse inputs and complex control. When your message, whether entertaining or inspiring, is felt and understood from the first row to the last, you know you\'ve got the right audio production team.',
                'content' => null,
                'meta_description' => 'Professional audio services for events. Sound reinforcement, mixing, and audio production.',
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'visual',
                'title' => 'Visual',
                'description' => 'Size matters and we get that. Whatever your event calls for, we\'re ready to scale it up and keep it sharp! No event is complete without stunning imagery. Displayed on LED walls, projection screens, or interactive displays, we bring your visual content to life.',
                'content' => null,
                'meta_description' => 'Professional visual services for events. LED displays, projection, and video production.',
                'sort_order' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'lighting',
                'title' => 'Lighting',
                'description' => 'Event lighting is a critical part of any show or performance, and StagePass Audio Visual\'s team is extremely skilled at lighting even the most intricate productions. Special event coordinators, marketing managers, and producers rely on the experts at StagePass Audio Visual, the behind-the-scenes boys and girls who bring it all together. We\'ll illuminate your event, beautifully.',
                'content' => '<p>Stagepass lighting designers and technicians pull together to deliver that extraordinary experience, finding that edge, drawing forth emotion with color, texture and movement. With our large inventory of intelligent lighting, they set the mood, paint the room and deliver the "eye candy" that draws the audience in and keeps them engaged. We understand lighting to mean much more than illumination. Choose from our wide array of solutions to communicate emotions, vigor and impact.</p>',
                'meta_description' => 'Professional event lighting services. Intelligent lighting, design, and production for memorable events.',
                'sort_order' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'lighting/trade-show-lighting',
                'title' => 'Trade Show Lighting',
                'description' => 'Stagepass Audio Visual Limited\'s vast experience has made us intimately familiar with convention center logistics. The day of a trade show can be a hectic time and it\'s probable that the last thing on your mind is the quality of the lighting in your booth, or the power distribution needed to make it all happen.',
                'content' => '<p>We can manage everything from individual booth lighting, right up to full exhibition production for event organizers. That includes the power distribution, labor, trucking, design and equipment, so you\'re left with more time to focus on showing off your business.</p>',
                'meta_description' => 'Trade show lighting services. Professional booth lighting and exhibition production.',
                'sort_order' => 9,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'lighting/corporate-event-lighting',
                'title' => 'Corporate Event Lighting',
                'description' => 'When choosing Stagepass Audio Visual Limited to light your corporate event, rest assured that we understand its importance and the setup it requires.',
                'content' => '<p>We understand how crucial the overall look is to any occasion or show, and reflect that in both equipment and personnel. The infrastructure required to create a fabulous looking event is not always fabulous looking itself. Technology is sometimes messy, but our crews know that you don\'t want to see the pieces needed to make it work – just the polished end product. We are experts at making the behind the scenes disappear. Our technicians also understand that discretion and privacy are hugely important, so confidentiality is always assured.</p>',
                'meta_description' => 'Corporate event lighting services. Professional lighting design for corporate events.',
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'lighting/festivals',
                'title' => 'Festivals',
                'description' => 'We also specialize in the unique demands of outdoor shows. Our company knows how to best prepare for the elements, while our innate flexibility and adaptability allow us to design creative solutions for the most difficult terrain. So you can put your fears to rest – we can and will adapt to your immediate needs and challenges in real time.',
                'content' => null,
                'meta_description' => 'Festival lighting services. Outdoor event lighting solutions for festivals and concerts.',
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'audio/sporting-events',
                'title' => 'Sporting Events',
                'description' => 'Sporting events and rallies are quite clearly loud by nature, so it\'s our duty to provide top-of-the-line audio equipment to rise above the roars of cheering fans.',
                'content' => '<p>These events are also often presented in very alternative venues, a challenge which requires equally creative solutions that some audio production companies simply can\'t handle. But at Stagepass Audio Visual Limited, we know we can. Halftime shows and promotional events mandate fast turnarounds, and our teams are masters at the impeccable planning and preparation needed to pull them off without a hitch.</p>',
                'meta_description' => 'Audio services for sporting events. Professional sound reinforcement for sports venues.',
                'sort_order' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'audio/audio-equipment-rentals',
                'title' => 'Audio Equipment Rentals',
                'description' => 'We maintain a large inventory of audio equipment in our warehouse. When you\'re searching for a simple solution of renting audio equipment, we\'re here to help.',
                'content' => null,
                'meta_description' => 'Audio equipment rentals. Professional sound equipment for rent in Nairobi.',
                'sort_order' => 13,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'audio/fashion-audio',
                'title' => 'Fashion Audio',
                'description' => 'Great fashion shows require great audio. Our audio solutions for fashion events ensure that every word, every note, and every sound is delivered with precision and clarity.',
                'content' => null,
                'meta_description' => 'Audio services for fashion shows. Professional sound for fashion events.',
                'sort_order' => 14,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'audio/nonprofit-events',
                'title' => 'Nonprofit Events',
                'description' => 'For the nonprofit industry, Stagepass Audio Visual Limited is skilled in delivering value-conscious engineering solutions for those working within limited budgets, but this doesn\'t mean you\'ll have to do without the best.',
                'content' => null,
                'meta_description' => 'Audio services for nonprofit events. Affordable professional audio solutions.',
                'sort_order' => 15,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'audio/corporate-event-audio',
                'title' => 'Corporate Event Audio',
                'description' => 'Corporate events require professional audio solutions that deliver clear, crisp sound for presentations, speeches, and entertainment. Our team ensures your message is heard clearly by every attendee.',
                'content' => null,
                'meta_description' => 'Corporate event audio services. Professional sound for corporate presentations and events.',
                'sort_order' => 16,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'audio/full-service-audio-packages',
                'title' => 'Full-Service Audio Packages',
                'description' => 'At Stagepass Audio Visual Limited, we offer comprehensive audio packages that include everything from planning and design to setup, operation, and teardown. Our full-service approach ensures a seamless audio experience for your event.',
                'content' => null,
                'meta_description' => 'Full-service audio packages. Complete audio production services for events.',
                'sort_order' => 17,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'visual/fashion',
                'title' => 'Fashion Visual',
                'description' => 'Great designs mandate great showcase presentations, and visual displays affect everything the audience perceives. The seasoned specialists at Stagepass Audio Visual Limited have been answering to high expectations for more than three decades and will bring that experience to your fashion event.',
                'content' => null,
                'meta_description' => 'Visual services for fashion shows. Professional video and display solutions for fashion events.',
                'sort_order' => 18,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'visual/corporate-event-video',
                'title' => 'Corporate Event Video',
                'description' => 'Corporate events require professional video solutions for presentations, live streaming, and content display. Our video services ensure your corporate message is delivered with clarity and impact.',
                'content' => null,
                'meta_description' => 'Corporate event video services. Professional video production for corporate events.',
                'sort_order' => 19,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'visual/trade-shows',
                'title' => 'Trade Shows',
                'description' => 'Trade shows require dynamic visual displays to capture attention and communicate your message effectively. Our visual solutions for trade shows include LED displays, projection mapping, and interactive displays.',
                'content' => null,
                'meta_description' => 'Visual services for trade shows. LED displays and video solutions for exhibitions.',
                'sort_order' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'visual/full-service-video-packages',
                'title' => 'Full-Service Video Packages',
                'description' => 'Our comprehensive video packages include everything from content creation and display design to setup, operation, and teardown. We handle all aspects of video production for your event.',
                'content' => null,
                'meta_description' => 'Full-service video packages. Complete video production services for events.',
                'sort_order' => 21,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => 'design-services/lighting-design',
                'title' => 'Lighting Design',
                'description' => 'If you\'re working with Stagepass Audio Visual Limited to secure the perfect lighting for your event, we\'re happy to provide for any design services you need. Our project managers work with designers every day, both our trusted creative professionals and those appointed by our clients.',
                'content' => '<p>Together, we create production drawings and lighting plots. By taking the time to invest in proper lighting design from the early planning stages, a cohesive overall aesthetic is assured, so every ambition for the event or show is sure to be met. Whether you are organizing a charity event in Nairobi or a weekend festival in Mombasa, Stagepass Audio Visual Limited is the partner you need.</p>',
                'meta_description' => 'Professional lighting design services. Custom lighting design and production drawings.',
                'sort_order' => 22,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        foreach ($servicePages as $page) {
            DB::table('service_pages')->updateOrInsert(
                ['slug' => $page['slug']],
                $page
            );
        }

        // Industry Pages
        $industryPages = [
            [
                'slug' => '1',
                'title' => 'Concerts',
                'description' => 'StagePass Audio visual has a long history in this industry, affording us a level of knowledge that can help you every step along the way. We maintain a vast inventory of equipment including the latest technology and our personnel have years of experience to know how to handle even the most complex setup. We understand that success is all about the preparation. We move in fast (and always accurately), set up efficiently, and ensure every detail is perfect for your concert event.',
                'content' => '<p>From intimate acoustic performances to large-scale arena concerts, StagePass Audio Visual has the expertise and equipment to make your event unforgettable. Our team understands the unique demands of live music events, from sound reinforcement that reaches every corner of the venue to lighting that enhances the performance and creates the perfect atmosphere.</p><p>We work closely with artists, promoters, and venue managers to deliver seamless audio-visual experiences that elevate every performance. Our comprehensive concert services include audio systems, lighting design, video displays, staging, and rigging – all executed with precision and professionalism.</p>',
                'meta_description' => 'Professional AV services for concerts and live music events. Expert audio, lighting, and staging solutions for concerts of all sizes.',
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => '2',
                'title' => 'Corporate Events',
                'description' => 'Where matters of business are concerned, tact and a respect for privacy are paramount. We know that you expect both discretion and confidentiality. With StagePass Audio visual, those considerations come guaranteed. We also pledge that all personnel are well-organized and handle all hardware and equipment in a neat and clean manner. We fully appreciate the need to present a professional overall aesthetic, so you can be assured that everything is handled with the utmost professionalism.',
                'content' => '<p>Corporate events require a different approach than entertainment events. We understand the importance of clear communication, professional presentation, and seamless execution. Whether you\'re hosting a product launch, annual conference, board meeting, or corporate gala, our team ensures your message is delivered with clarity and impact.</p><p>Our corporate event services include professional audio systems for presentations, video displays for content sharing, lighting that enhances the professional atmosphere, and staging that reflects your company\'s brand and values. We work discreetly and efficiently, ensuring minimal disruption to your business operations.</p>',
                'meta_description' => 'Professional AV services for corporate events. Discreet, reliable audio-visual solutions for business meetings, conferences, and corporate gatherings.',
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => '3',
                'title' => 'Fashion',
                'description' => 'The fashion industry is a fast-paced and ever-evolving universe. To ensure success at every fashion show, with every step a model takes on the catwalk, you need a partner you can rely on. StagePass Audio visual is that partner. Our vast experience with fashion events has given us the knowledge and the skill to work quickly and with precision. There\'s only one chance to get it right, and at StagePass, we make sure we get it right every time.',
                'content' => '<p>Fashion shows demand perfection. Every detail matters, from the lighting that highlights the garments to the audio that sets the mood and pace. Our team understands the unique requirements of fashion events and works closely with designers and event coordinators to create stunning runway experiences.</p><p>We provide specialized lighting design that showcases fabrics, colors, and textures beautifully, professional audio systems for music and commentary, video displays for brand presentations, and staging solutions that complement the fashion aesthetic. Our experience in the fashion industry ensures flawless execution for your runway shows, presentations, and fashion events.</p>',
                'meta_description' => 'Professional AV services for fashion shows and events. Specialized lighting, audio, and staging solutions for the fashion industry.',
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => '4',
                'title' => 'Theater & Dance',
                'description' => 'StagePass Audio visual has a long history providing technical support for theater and dance events. Success of these performances is all about preparation and full knowledge of the venue space and audience expectations. At StagePass Audio visual, we guarantee that all the services we provide for theater and dance events will exceed your expectations. Working with live performances, we pride ourselves on our ability to be flexible and adapt to the dynamic nature of theatrical productions.',
                'content' => '<p>Theater and dance performances require a deep understanding of artistic vision and technical precision. Our team works closely with directors, choreographers, and performers to bring their creative vision to life through expertly designed lighting, crystal-clear audio, and seamless technical execution.</p><p>We understand the unique challenges of live theater and dance, from quick scene changes to complex lighting cues that enhance the emotional impact of performances. Our services include theatrical lighting design, sound reinforcement for dialogue and music, video projection for set design, and technical support that ensures every performance runs smoothly.</p>',
                'meta_description' => 'Professional AV services for theater and dance performances. Theatrical lighting, sound, and technical support for live performances.',
                'sort_order' => 4,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => '5',
                'title' => 'Gala Dinners',
                'description' => 'At Stagepass Audio Visual, we specialize in large gatherings and properly prepared for any size of the audience. We employ creative solutions to manage big audiences, quickly and efficiently adapt to the changing needs of your event and guarantee the safety and satisfaction of all in attendance.',
                'content' => '<p>Gala dinners and formal events require elegance, sophistication, and flawless execution. Our team creates beautiful atmospheres that enhance the dining experience while ensuring clear audio for speeches, presentations, and entertainment. We understand that gala events are often fundraising or recognition events where every detail contributes to the overall success.</p><p>Our gala dinner services include elegant lighting design that creates the perfect ambiance, professional audio systems for speeches and entertainment, video displays for presentations and recognition, staging for speakers and performers, and comprehensive technical support throughout your event. We work with event planners to ensure seamless coordination and execution.</p>',
                'meta_description' => 'Professional AV services for gala dinners and formal events. Elegant lighting, audio, and staging solutions for sophisticated gatherings.',
                'sort_order' => 5,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => '6',
                'title' => 'Trade Shows',
                'description' => 'We are proud of our extensive history of providing production support for trade shows. This allows us to understand and navigate the complex – and usually unique – logistics of convention centers around the country to provide the very best for our clients every single time.',
                'content' => '<p>Trade shows present unique challenges with tight timelines, complex logistics, and the need to make a strong impression in a competitive environment. Our extensive experience with trade shows and exhibitions means we understand convention center logistics, power distribution requirements, and the fast-paced nature of these events.</p><p>We provide comprehensive trade show services including booth lighting, audio systems for presentations, video displays and LED walls, staging and platform solutions, power distribution, and full production support. Whether you need services for a single booth or full exhibition production, our team delivers reliable, professional solutions that help your business stand out.</p>',
                'meta_description' => 'Professional AV services for trade shows and exhibitions. Booth lighting, audio, video displays, and full production support for trade shows.',
                'sort_order' => 6,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => '7',
                'title' => 'Sporting Events',
                'description' => 'StagePass Audio visual has provided services for halftime shows, rallies and promotional events, often in very alternative venues. Events like these usually call for a fast turnaround. Impeccable preparation and planning allow us to be in place and on time at each and every sporting event.',
                'content' => '<p>Sporting events require robust audio systems that can rise above the roar of cheering fans, dynamic lighting that enhances the excitement, and reliable technical support that can handle the fast-paced nature of sports entertainment. Our team has extensive experience with stadium events, halftime shows, and sporting event productions.</p><p>We provide powerful audio systems designed for large venues, dynamic lighting for halftime shows and entertainment, video displays and scoreboards, staging for presentations and performances, and rapid setup and teardown services. Our expertise in alternative venues and fast turnarounds ensures your sporting event runs smoothly from start to finish.</p>',
                'meta_description' => 'Professional AV services for sporting events. Stadium audio, halftime show lighting, and technical support for sports venues.',
                'sort_order' => 7,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'slug' => '8',
                'title' => 'Nonprofit Events',
                'description' => 'Nonprofit organizations typically have to work within limited budgets. We understand that it can be overwhelming, but our experts are here to work with you to find a solution that meets your expectations (and your budget). Our project managers are dedicated to providing a neat, clean and organized look for every aspect of your event while delivering professional-quality results.',
                'content' => '<p>We believe that nonprofit organizations deserve the same high-quality audio-visual services as any other client, regardless of budget constraints. Our team works closely with nonprofit event organizers to create cost-effective solutions that don\'t compromise on quality or professionalism.</p><p>Our nonprofit event services include affordable audio systems for presentations and entertainment, professional lighting, video displays for content sharing, staging solutions, and comprehensive technical support. We understand the importance of your mission and work to ensure your events are successful in achieving your goals, whether that\'s fundraising, awareness, or community engagement.</p>',
                'meta_description' => 'Affordable professional AV services for nonprofit events. Cost-effective audio-visual solutions for nonprofit organizations.',
                'sort_order' => 8,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        foreach ($industryPages as $page) {
            DB::table('industry_pages')->updateOrInsert(
                ['slug' => $page['slug']],
                $page
            );
        }
    }
}
